name: Build And Push to ECR
description: Build And Push to ECR
inputs:
  PIPELINE_USER_ACCESS_KEY_ID:
    description: "TF Pipeline User Access Key"
    required: true
  PIPELINE_USER_SECRET_ACCESS_KEY:
    description: "TF Pipeline User Secret Access Key"
    required: true
  AWS_REGION:
    description: "AWS Region"
    required: true
  REPOSITORY_NAME:
    description: "Repository Name"
    required: true
  ENVIRONMENT_LOWER:
    description: "Environment name in lower case('production', 'staging')"
    required: true
  COMPONENT_PATH:
    description: "Component path of the component to be deployed (./cms, ./client ...)"
    required: true
  DRY_RUN:
    description: "Makes the action work in Dry Run Mode"
    required: false
    default: "false" # WARNING Input type is not supported in composite actions. Must treat it as a string

#NOTE Actions needs to specify the shell to use on every steps that uses "runs:" https://stackoverflow.com/questions/71041836/github-actions-required-property-is-missing-shell

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.PIPELINE_USER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.PIPELINE_USER_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build, tag, and push Client image to Amazon ECR
      if: ${{ inputs.DRY_RUN == 'false' || inputs.DRY_RUN == '' }}
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.COMPONENT_PATH }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        file: ${{ inputs.COMPONENT_PATH }}/Dockerfile.prod
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.REPOSITORY_NAME }}:${{ github.sha }}
          ${{ steps.login-ecr.outputs.registry }}/${{ inputs.REPOSITORY_NAME }}:${{ inputs.ENVIRONMENT_LOWER }}
