version:  '3.8'
services:
    data_processing-notebooks:
      build:
        context: .
      volumes:
        - ./data:/home/mambauser/data
        - ./notebooks:/home/mambauser/notebooks
        - ./src:/home/mambauser/src
      ports:
        - 8888:8888
        - 8787:8787  # dask dashboard
      container_name: data_processing_notebooks
      env_file: .env
